---
- name: Install ctop wrapper script
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      set -e -u
      podman run --rm --interactive --tty \
        --name=ctop \
        --volume "$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock:ro" \
        quay.io/vektorlab/ctop:latest
    dest: /usr/local/bin/ctop
    mode: "0755"
