---
# Check with `cat /etc/sysctl.conf` & `cat /proc/sys/vm/swappiness`
- name: Set vm.swappiness
  become: true
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    sysctl_set: true
